#!/usr/bin/python3
import sys

for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

ans = 0
for line in sys.stdin:
    line = line.rstrio()
        ans += tonum(line)

print(ans)
